# Generated by Django 5.1.5 on 2025-05-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('idlevel', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('idnotification', models.AutoField(primary_key=True, serialize=False)),
                ('verb', models.CharField(max_length=30, verbose_name='Verbo')),
                ('description', models.CharField(max_length=80, verbose_name='Descripción')),
                ('public', models.BooleanField(default=True, verbose_name='Público')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('emailed', models.BooleanField(default=False, verbose_name='Enviado por correo')),
                ('idlevel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='notificaciones.level', verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400, verbose_name='Mensaje')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('read', models.BooleanField(default=False, verbose_name='Leído')),
                ('target_id', models.PositiveIntegerField(verbose_name='ID de Entidad Objetivo')),
                ('idnotification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='notificaciones.notification', verbose_name='Notificación')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype', verbose_name='Tipo de Entidad Objetivo')),
            ],
            options={
                'verbose_name': 'Notificación de Usuario',
                'verbose_name_plural': 'Notificaciones de Usuarios',
                'db_table': 'notifications_auth_user',
            },
        ),
    ]
