# Generated by Django 5.1.5 on 2025-07-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationcustomuser',
            options={'ordering': ['-created'], 'verbose_name': 'Notificación de Usuario', 'verbose_name_plural': 'Notificaciones de Usuarios'},
        ),
    ]
