# Generated by Django 5.1.5 on 2025-05-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Givas',
            fields=[
                ('idgiva', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_giva', models.CharField(max_length=30, verbose_name='Descripción')),
                ('valoriva', models.IntegerField(verbose_name='Valor Iva')),
            ],
            options={
                'verbose_name': 'Graba Iva',
                'verbose_name_plural': 'Graba Ivas',
                'db_table': 'givas',
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('codigoarticulo', models.CharField(max_length=10, unique=True, verbose_name='Código de Producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion_articulo', models.CharField(max_length=100, verbose_name='Descripción')),
                ('tiene_fecha_caduca', models.BooleanField(default=False, verbose_name='¿Tiene fecha de caducidad?')),
                ('manejo_por_lotes', models.BooleanField(default=False, verbose_name='¿Se maneja por lotes?')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Alerta Stock Mínimo')),
                ('stock_maximo', models.IntegerField(default=1, verbose_name='Alerta Stock Máximo')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('utilidad', models.IntegerField(verbose_name='Utilidad')),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Venta')),
                ('estado_articulo', models.IntegerField(default=1, verbose_name='Estado')),
                ('idcategoriaarticulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categorias.categoriaarticulos', verbose_name='Categoría')),
                ('idgiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.givas', verbose_name='Graba Iva')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulos',
            },
        ),
    ]
