# Generated by Django 5.1.5 on 2025-07-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'ordering': ['-estado_articulo', 'descripcion_articulo'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
    ]
