# Generated by Django 5.1.5 on 2025-07-15 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulos_options'),
        ('categorias', '0003_subcategoriaarticulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='manejo_por_lotes',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='tiene_fecha_caduca',
        ),
        migrations.AddField(
            model_name='articulos',
            name='idsubcategoriaarticulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categorias.subcategoriaarticulos', verbose_name='Subcategoría'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='idgiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.givas', verbose_name='Iva'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='stock_maximo',
            field=models.IntegerField(default=1, verbose_name='Stock Máximo'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='stock_minimo',
            field=models.IntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
    ]
