# Generated by Django 5.1.5 on 2025-07-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_remove_articulos_manejo_por_lotes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('idtalla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=5, unique=True, verbose_name='Talla')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'db_table': 'tallas',
            },
        ),
        migrations.AddField(
            model_name='articulos',
            name='tallas',
            field=models.ManyToManyField(related_name='articulos', to='articulos.talla', verbose_name='Tallas Disponibles'),
        ),
    ]
