# Generated by Django 5.1.5 on 2025-05-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipodocumentos',
            fields=[
                ('idtipodocumento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipodocumento', models.CharField(max_length=25, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipo Documentos',
                'db_table': 'tipodocumentos',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('numerodocumento', models.CharField(max_length=13, unique=True, verbose_name='Número de Identificación')),
                ('nombre_cliente', models.CharField(max_length=60, verbose_name='Nombre')),
                ('direccion_cliente', models.CharField(max_length=100, verbose_name='Dirección')),
                ('correo_cliente', models.EmailField(max_length=80, unique=True, verbose_name='Correo')),
                ('telefono_cliente', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono')),
                ('celular_cliente', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('estado_cliente', models.IntegerField(default=1, verbose_name='Estado')),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.tipodocumentos', verbose_name='Tipo de Identificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
    ]
