# Generated by Django 5.1.5 on 2025-05-08 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='detalle_compras',
            name='codigoarticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='articulos.articulos', verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='detalle_compras',
            name='idcompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='compras.compras', verbose_name='Compra'),
        ),
    ]
