# Generated by Django 5.1.5 on 2025-07-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'ordering': ['-idcompra', '-fecha_compra'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
