# Generated by Django 5.1.5 on 2025-07-20 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_talla_articulos_tallas'),
        ('compras', '0003_alter_compras_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compras',
            name='talla',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='articulos.talla', verbose_name='Talla'),
            preserve_default=False,
        ),
    ]
