# Generated by Django 5.1.5 on 2025-07-20 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_talla_articulos_tallas'),
        ('compras', '0004_detalle_compras_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompraTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.detalle_compras')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.talla')),
            ],
            options={
                'verbose_name': 'Talla en Detalle de Compra',
                'verbose_name_plural': 'Tallas en Detalles de Compra',
                'db_table': 'detalle_compra_talla',
            },
        ),
    ]
