# Generated by Django 5.1.5 on 2025-07-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_detallecompratalla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_compras',
            name='talla',
        ),
        migrations.DeleteModel(
            name='DetalleCompraTalla',
        ),
    ]
