# Generated by Django 5.1.5 on 2025-05-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('ruc_proveedor', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('nombrecontacto_proveedor', models.CharField(max_length=60, verbose_name='Contacto')),
                ('nombre_proveedor', models.CharField(max_length=60, verbose_name='Nombre')),
                ('direccion_proveedor', models.CharField(max_length=100, verbose_name='Dirección')),
                ('correo_proveedor', models.EmailField(max_length=80, unique=True, verbose_name='Correo')),
                ('telefono_proveedor', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono')),
                ('celular_proveedor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('estado_proveedor', models.IntegerField(default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
    ]
