# Generated by Django 5.1.5 on 2025-07-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotes',
            options={'ordering': ['codigoarticulo', 'fecha_caducidad'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
    ]
