# Generated by Django 5.1.5 on 2025-05-08 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formapagos',
            fields=[
                ('idformapago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_formapago', models.CharField(max_length=60, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Forma Pago',
                'verbose_name_plural': 'Forma Pagos',
                'db_table': 'formapagos',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Concepto')),
                ('fecha_venta', models.DateField(verbose_name='Fecha')),
                ('subtotal_tarifa0', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tarifa 0')),
                ('subtotal_tarifa12', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tarifa 15')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('valoriva', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('estado_venta', models.IntegerField(default=1, verbose_name='Estado')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idpago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('idformapago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ventas.formapagos', verbose_name='Forma Pago')),
                ('idventa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ventas.ventas', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Detalle_ventas',
            fields=[
                ('iddetalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Unitario')),
                ('valordescuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Dscto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('codigoarticulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='articulos.articulos', verbose_name='Artículo')),
                ('idventa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ventas.ventas', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalle Ventas',
                'db_table': 'detalle_ventas',
            },
        ),
    ]
