# Generated by Django 5.1.5 on 2025-05-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriaarticulos',
            fields=[
                ('idcategoriaarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_categoriaarticulo', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría Artículo',
                'verbose_name_plural': 'Categoría Artículos',
                'db_table': 'categoriaarticulos',
            },
        ),
    ]
