# Generated by Django 5.1.5 on 2025-07-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaarticulos',
            options={'ordering': ['descripcion_categoriaarticulo'], 'verbose_name': 'Categoría Artículo', 'verbose_name_plural': 'Categoría Artículos'},
        ),
    ]
