# Generated by Django 5.1.5 on 2025-07-13 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoriaarticulos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoriaarticulos',
            fields=[
                ('idsubcategoriaarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_subcategoriaarticulo', models.CharField(max_length=100, verbose_name='Descripción de la subcategoría')),
                ('idcategoriaarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='categorias.categoriaarticulos', verbose_name='Categoría asociada')),
            ],
            options={
                'verbose_name': 'Subcategoría Artículo',
                'verbose_name_plural': 'Subcategorías Artículos',
                'db_table': 'subcategoriaarticulos',
                'ordering': ['descripcion_subcategoriaarticulo'],
            },
        ),
    ]
