# Generated by Django 5.1.5 on 2025-05-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('idciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('idprovincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('RUC', models.CharField(max_length=13, verbose_name='RUC')),
                ('razonsocial', models.CharField(max_length=80, verbose_name='Razón Social')),
                ('nombrecomercial', models.CharField(max_length=80, verbose_name='Nombre Comercial')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Logo de la Empresa')),
                ('direccion1', models.CharField(max_length=100, verbose_name='Dirección Matriz')),
                ('direccion2', models.CharField(max_length=100, verbose_name='Dirección Sucursal')),
                ('correo_empresa', models.EmailField(max_length=80, verbose_name='Correo')),
                ('telefono_empresa', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono')),
                ('celular_empresa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('cedularepresentantelegal', models.CharField(max_length=10, verbose_name='Cedula Representante Legal')),
                ('nombrerepresentantelegal', models.CharField(max_length=50, verbose_name='Nombre Representante Legal')),
                ('rutaarchivogenerados', models.CharField(max_length=100, verbose_name='Ruta de Archivos')),
                ('estado_empresa', models.IntegerField(default=1, verbose_name='Estado')),
                ('idciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.ciudades', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'datos_empresa',
            },
        ),
        migrations.AddField(
            model_name='ciudades',
            name='idprovincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.provincias', verbose_name='Provincia'),
        ),
    ]
